server:
  port: 8888
  max-http-header-size: 10240

spring:
  mvc:
    view:
      prefix: /pages
      suffix: .html
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  freemarker:
    prefix:
    suffix: .html
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html;
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    request-context-attribute: rc
    template-loader-path: classpath:/pages/
  task:
    execution:
      pool:
        max-threads: 16
        queue-capacity: 100
        keep-alive: 10s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    filters: wall,mergeStat
    data-source-name: test
